// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7knLM44xZ2tXhYn4peg7tZsmyy2A_NiI',
    appId: '1:820774877337:web:dc3e5f5ad3350b1f68a008',
    messagingSenderId: '820774877337',
    projectId: 'chat-app-da079',
    authDomain: 'chat-app-da079.firebaseapp.com',
    storageBucket: 'chat-app-da079.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDv8QKUiJ-kPcDqVkSBz9rqjAeGMHuO3qw',
    appId: '1:820774877337:android:c3c88d1553b7ab6e68a008',
    messagingSenderId: '820774877337',
    projectId: 'chat-app-da079',
    storageBucket: 'chat-app-da079.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJTqsZ7R_KO9QjogmEYTC0u1GNNT3U52I',
    appId: '1:820774877337:ios:929d0ba2baa04c5e68a008',
    messagingSenderId: '820774877337',
    projectId: 'chat-app-da079',
    storageBucket: 'chat-app-da079.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJTqsZ7R_KO9QjogmEYTC0u1GNNT3U52I',
    appId: '1:820774877337:ios:18670ebbac76032c68a008',
    messagingSenderId: '820774877337',
    projectId: 'chat-app-da079',
    storageBucket: 'chat-app-da079.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
